version: "3.7"
services:
  mysql:
    image: mysql:5.7
    environment:
      -  MYSQL_ROOT_PASSWORD=password
      -  MYSQL_DATABASE=accounts_list
    volumes:
      - type: volume
        source: mysqldataa
        target: /var/lib/mysql
  backend:
    image: alinawazmamdani/backend
    depends_on:
      - mysql

  nginx:
    build: ./nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - backend

volumes:
  mysqldataa:

